Controllers/PipelineController.cs
using ClosedXML.Excel;
using DocumentFormat.OpenXml.InkML;
using FlexicodeConnectors.Helper;
using FlexicodeConnectors.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using NPOI.HSSF.UserModel;
using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.OleDb;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Mime;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using System.Threading;
using System.Threading.Tasks;
using DataTable = System.Data.DataTable;


namespace FlexicodeConnectors.Controllers
{
    public class PipelineController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly HttpClient _httpClient;
        // Specify the folder path within your project where you want to store the file.
        //string folderPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "uploads") ;

        string folderPath = "";
        string macroFolderPath = "";
        string hostingfor = "";
        string _slash = "";

        public PipelineController(IConfiguration configuration, HttpClient httpClient)
        {
            _configuration = configuration;
            _httpClient = httpClient;
            hostingfor = _configuration.GetConnectionString("HostingFor");
            if (hostingfor.Trim() == "Linux")
            {
                _slash = "/";
            }
            else
            {
                _slash = "\\";
            }

            folderPath = Path.Combine(Directory.GetCurrentDirectory(), "uploads") + _slash;//_configuration.GetConnectionString("Uploadpath"); //WINDOWS Server
            macroFolderPath = Path.Combine(Directory.GetCurrentDirectory(), "macros") + _slash;//_configuration.GetConnectionString("Uploadpath"); //WINDOWS Server
            ConnectorApi _api = new ConnectorApi(configuration);

        }

        //byte[] fileBytes;
        public IActionResult PipelineList()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> PipelineNew(int id)

        {
            //folderPath = _configuration.GetConnectionString("Uploadpath");

            //Connector Drop Down Binding
            List<ConnectionDto> lovconn = new List<ConnectionDto>();
            var results = "";
            ConnectorApi _api = new ConnectorApi(_configuration);
            HttpClient client = _api.Initial();
            HttpResponseMessage res = await client.GetAsync("Pipeline/GetConnectorsForDropdown");
            if (res.IsSuccessStatusCode)
            {
                results = res.Content.ReadAsStringAsync().Result;
                lovconn = JsonConvert.DeserializeObject<List<ConnectionDto>>(results);
            }
            ViewBag.Connectors = lovconn;
            ViewBag.pipeline_id = id;
            ViewBag.fileuploaddir = folderPath;

            //Label Data Info Binding
            List<PipelineModel> objpplinfo = new List<PipelineModel>();

            using (client = _api.Initial())
            {
                res = await client.GetAsync($"Pipeline/Getpipelineinfo?pipelinegid={id}");
                if (res.IsSuccessStatusCode)
                {
                    results = await res.Content.ReadAsStringAsync(); // Use async method
                    objpplinfo = JsonConvert.DeserializeObject<List<PipelineModel>>(results);
                }
            }

            if (objpplinfo.Count > 0)
            {
                // Set ViewData properties based on the retrieved data.
                ViewData["infopplname"] = objpplinfo[0].pipeline_name;
                ViewData["infoconname"] = objpplinfo[0].connection_name;
                ViewData["infosrctbl"] = objpplinfo[0].table_view_query_desc;
            }

            Connection masterData = new Connection();
            // var results = "";
            client = new HttpClient();
            client = _api.Initial();
            HttpResponseMessage res1 = await client.GetAsync($"DataProcessings/GetMasterDatawithCode?parentCode={"DAP"}");
            var connectionModel = new Connection();
            if (res1.IsSuccessStatusCode)
            {
                results = res1.Content.ReadAsStringAsync().Result;
                //masterData.masterDatas = JsonConvert.DeserializeObject<List<Masters>>(results);
                connectionModel = new Connection
                {
                    masterDatas = JsonConvert.DeserializeObject<List<Masters>>(results)
                        .Select(c => new SelectListItem
                        {
                            Value = c.master_code.ToString(),
                            Text = c.master_name
                        })
                        .ToList()
                };

            }
            return View(connectionModel);
        }
        [HttpGet]
        public async Task<JsonResult> Readpipeline(int id)
        {
            //folderPath = _configuration.GetConnectionString("Uploadpath");

            PipelineModel objpipeline = new PipelineModel();
            var results = "";
            ConnectorApi _api = new ConnectorApi(_configuration);
            HttpClient client = _api.Initial();
            HttpResponseMessage res = await client.GetAsync("Pipeline/GetPipeline?id=" + id);
            if (res.IsSuccessStatusCode)
            {
                results = res.Content.ReadAsStringAsync().Result;
                objpipeline = JsonConvert.DeserializeObject<PipelineModel>(results);
                objpipeline.file_path = folderPath;
                string ext = "";
                if (objpipeline.source_file_name != "" && objpipeline.source_file_name != null)
                {
                    string[] parts = objpipeline.source_file_name.Split('.');
                    ext = "." + parts.Last();

                }

                HttpContext.Session.SetString("session_pplcodefilename", objpipeline.pipeline_code + ext);
            }

            return Json(objpipeline);
        }

        [HttpGet]
        public async Task<JsonResult> GetsrcDbType(string Connection_code)
        {
            Connection objres = new Connection();
            var results = "";
            ConnectorApi _api = new ConnectorApi(_configuration);
            HttpClient client = _api.Initial();
            HttpResponseMessage res = await client.GetAsync("Pipeline/GetSourcedbType?connection_code=" + Connection_code);
            if (res.IsSuccessStatusCode)
            {
                results = res.Content.ReadAsStringAsync().Result;
                objres = JsonConvert.DeserializeObject<Connection>(results);
            }

            return Json(objres);
        }

        [HttpGet]
        public async Task<JsonResult> GellAllPipelines(string run_type, string pipeline_status)
        {
            try
            {
                List<PipelineModel> pipelines = new List<PipelineModel>();
                var results = "";
                ConnectorApi _api = new ConnectorApi(_configuration);
                HttpClient client = _api.Initial();
                HttpResponseMessage res = await client.GetAsync("Pipeline/GetPipelines?runtype=" + run_type + "&pipeline_status=" + pipeline_status);
                if (res.IsSuccessStatusCode)
                {
                    results = res.Content.ReadAsStringAsync().Result;
                    pipelines = (List<PipelineModel>)JsonConvert.DeserializeObject<List<PipelineModel>>(results);
                }
                return Json(pipelines);
            }
            catch(Exception ex)
            {
                return Json(ex.Message);
            }                        
        }

        [HttpGet]
        public async Task<JsonResult> Getconndblist(string connection_code)
        {
            List<DatabaseInfo> dbinfo = new List<DatabaseInfo>();

            var results = "";
            ConnectorApi _api = new ConnectorApi(_configuration);
            HttpClient client = _api.Initial();
            HttpResponseMessage res = await client.GetAsync("Pipeline/GetDatabaseNames?connection_code=" + connection_code);
            HttpContext.Session.SetString("session_sheetname", "");
            HttpContext.Session.SetString("session_filename", "");

            if (res.IsSuccessStatusCode)
            {
                results = res.Content.ReadAsStringAsync().Result;
                dbinfo = JsonConvert.DeserializeObject<List<DatabaseInfo>>(results);
            }
            return Json(dbinfo);
        }

        [HttpPost]
        public async Task<JsonResult> UploadFile(string pipeline_code, IFormFile file)
        {
            //folderPath = _configuration.GetConnectionString("Uploadpath");

            string errormsg = "";
            var filePath = "";
            try
            {
                if (file != null && file.Length > 0)
                {
                    errormsg = folderPath;

                    //Trace Error
                    //var errorLog = new ErrorLog
                    //{
                    //    in_errorlog_pipeline_code = pipeline_code,
                    //    in_errorlog_scheduler_gid = 0,
                    //    in_errorlog_type = "folderPath - Method Name : UploadFile",
                    //    in_errorlog_exception = errormsg,
                    //    in_created_by = ""
                    //};
                    //IsErrorlog(errorLog);

                    // Create the folder if it doesn't exist.
                    if (!Directory.Exists(folderPath))
                    {
                        Directory.CreateDirectory(folderPath);
                    }

                    string[] parts = file.FileName.Split('.');

Views/Report/ImportedFileInfo.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html>
<style>
    .refresh {
        width: 100px;
        background: #118a2d;
        border-radius: 5px;
        font-weight: bold;
        color: #ffff;
        border: 0 none;
        border-radius: 5px;
        cursor: pointer;
        padding: 8px 5px;
        /* margin: 10px 5px;*/
    }

    .text-2xl {
        font-size: 1.5rem !important;
    }

    .font-bold {
        font-weight: 700 !important;
    }
</style>

<body>
    <div>
        <div class="row" style="height:auto;">
            <div class="col-md-12">
                @*<div class="content-wrapper" style="padding:10px;">*@
                <div style="padding:10px;">
                    <div class="row" style="padding-bottom: 10px;">
                        <div class="col-md-4 font-bold text-2xl">
                            FILE IMPORT INFO
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            <label class="form-label">Period From</label>
                            <span id="txt_importfrom" class="mandatory" style="display:none;">*</span>
                            <br>
                            <input type="text" class="form-control" id="import_from" name="import_from" placeholder="Select start date">
                        </div>

                        <div class="col-md-3">
                            <label class="form-label">Period To</label>
                            <span id="txt_importto" class="mandatory" style="display:none;">*</span>
                            <br>
                            <input type="text" class="form-control" id="import_to" name="import_to" placeholder="Select end date">
                        </div>
                        <div class="col-md-3">
                            <input style="float: left;margin-top: 8%;" type="button" id='btn_refresh' onclick="RefreshData()" class="refresh" value="Refresh" />
                        </div>
                    </div>
                    <fieldset>
                        <div class="form-card" style="height: 70vh;margin-top:1%;">
                            <div class="row" style="padding: 0px 16px;">
                                <div id="FileImportGrid"></div>
                            </div>
                        </div>
                    </fieldset>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
<script>
    $(document).ready(function () {
        const urlParams = new URLSearchParams(window.location.search);
        let userCode = "";
        if (urlParams != "") {
            userCode = urlParams.get('user_code');
        }
        else {
            userCode = 'Blank';
        }
        sessionStorage.setItem("userCode", userCode);


    // Initialize From DateTimePicker
    var fromPicker = $("#import_from").kendoDateTimePicker({
        format: "dd-MM-yyyy HH:mm:ss",
        parseFormats: ["yyyy-MM-dd HH:mm:ss", "yyyy-MM-ddTHH:mm:ss", "MM/dd/yyyy hh:mm tt"],
        value: null,
        change: function () {
            var fromVal = this.value();
            var toVal = toPicker.value();

            // Enforce to >= from
            if (toVal && fromVal && toVal < fromVal) {
                  jAlert("Period From Cannot be greater than Period To", "Flexi Connector");
                  $('#btn_refresh').prop('disabled', true);
                  return
            }
            $('#btn_refresh').prop('disabled', false);
            $("#import_from").data("kendoDateTimePicker").value(fromVal);
        }
    }).data("kendoDateTimePicker");

    // Initialize To DateTimePicker
    var toPicker = $("#import_to").kendoDateTimePicker({
        format: "dd-MM-yyyy HH:mm:ss",
        parseFormats: ["yyyy-MM-dd HH:mm:ss", "yyyy-MM-ddTHH:mm:ss", "MM/dd/yyyy hh:mm tt"],
        value: null,
        change: function () {
            var toVal = this.value();
            var fromVal = fromPicker.value();

            if (fromVal && toVal && toVal < fromVal) {
                jAlert("Period To Cannot be less than Period From", "Flexi Connector");
                $('#btn_refresh').prop('disabled', true);
                  return
            }
            $('#btn_refresh').prop('disabled', false);
            $("#import_to").data("kendoDateTimePicker").value(toVal);
        }
    }).data("kendoDateTimePicker");

        listgrid([]);
    });


</script>
<script>

    // Helper function to convert JS Date to MySQL format
    function toMySQLDateTime(jsDate) {
        if (!jsDate) return "";
        const pad = (n) => n < 10 ? '0' + n : n;
        return jsDate.getFullYear() + '-' +
            pad(jsDate.getMonth() + 1) + '-' +
            pad(jsDate.getDate()) + ' ' +
            pad(jsDate.getHours()) + ':' +
            pad(jsDate.getMinutes()) + ':' +
            pad(jsDate.getSeconds());
    }

      function RefreshData() {
        var fromDateObj = $("#import_from").data("kendoDateTimePicker").value();
        var toDateObj = $("#import_to").data("kendoDateTimePicker").value();

        var from_date = toMySQLDateTime(fromDateObj);
        var to_date = toMySQLDateTime(toDateObj);

        // Now from_date and to_date are MySQL-formatted strings
        GetimportedfileList(from_date, to_date);
    }

    function GetimportedfileList(fromdate, todate) {
        $.ajax({
            type: 'GET',
            url: '@Url.Action("GellImportedFileInfo", "Report")?from_date=' + fromdate + "&to_date=" + todate,
            contentType: false,
            processData: false,
            cache: false,
            success: function (response) {
                var res = JSON.parse(response)
                 var $grid = $("#FileImportGrid");

                // destroy previous grid if exists
                if ($grid.data("kendoGrid")) {
                    $grid.data("kendoGrid").destroy();
                    $grid.empty(); // remove leftover DOM
                }
                listgrid(res);
            },
            error: function (er) {
                alert(er)
                console.log(er)
            }
        });
    }

</script>
<script>

    function listgrid(data) {
        try {
            $("#FileImportGrid").kendoGrid({
                 toolbar: ["excel"],
                excel: {
                    fileName: "FileimportedDetails.xlsx",
                    filterable: true,
                    allPages: true
                },
                dataSource: {
                    data: data,
                    schema: {
                        model: {
                            fields: {
                                pipeline_code_name: { type: "string" },
                                dataset_code_name: { type: "string" },
                                run_type: { type: "string" },
                                file_name: { type: "string" },
                                scheduler_start_date: { type: "string" },
                                scheduler_end_date: { type: "string" },
                                import_rec_count: { type: "integer" },
                                valid_rec_count: { type: "integer" },
                                Error_rec_count: { type: "integer" },
                                dataset_moved_count: { type: "integer" },
                                scheduler_status: { type: "string" },
                                errorlog_exception: { type: "string" },
                                import_by: { type: "string" },
                                scheduler_gid: { type: "integer" }
                            }
                        }
                    },
                    pageSize: 15
                },
                height: 400,
                width: 1058,
                pageable: true,
                sortable: true,
                filterable: true,
                selectable: "single",
                columns: [
                    { field: "pipeline_code_name", title: "Pipeline Code & Name", width: 200 },
                    { field: "dataset_code_name", title: "Dataset Code & Name", width: 200 },
                    { field: "run_type", title: "Run Type", width: 100 },
                    { field: "file_name", title: "File Name", width: 200 },
                    { field: "scheduler_start_date", title: "Scheduler start Date", width: 100,
                    template: "#= kendo.toString(kendo.parseDate(scheduler_start_date), 'yyyy-MM-dd HH:mm:ss') #"},
                    { field: "scheduler_end_date", title: "Scheduler end Date", width: 100 ,
                    template: "#= kendo.toString(kendo.parseDate(scheduler_end_date), 'yyyy-MM-dd HH:mm:ss') #"},
                    { field: "import_rec_count", title: "Imported Rec Count", width: 100 },
                    { field: "valid_rec_count", title: "Valid Rec Count", width: 100 },
                    { field: "Error_rec_count", title: "Error Rec Count", width: 100 },
                    { field: "dataset_moved_count", title: "Dataset Moved Count", width: 100 ,hidden: true},
                    { field: "scheduler_status", title: "Scheduler status", width: 100},
                    { field: "errorlog_exception", title: "Error Exception", width: 100},
                    { field: "import_by", title: "Import By", width: 100},
                    { field: "scheduler_gid", title: "Scheduler gid", width: 100}
                ],

                resizable: true
            });
        } catch (err) {
            alert(err);
        }
    }

</script>

Views/Report/PipelineDatasetInfo.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html>
<style>
    .refresh {
        width: 100px;
        background: #118a2d;
        border-radius: 5px;
        font-weight: bold;
        color: #ffff;
        border: 0 none;
        border-radius: 5px;
        cursor: pointer;
        padding: 8px 5px;
        /* margin: 10px 5px;*/
    }

    .text-2xl {
        font-size: 1.5rem !important;
    }

    .font-bold {
        font-weight: 700 !important;
    }
</style>

<body>
    <div>
        <div class="row" style="height:auto;">
            <div class="col-md-12">
                @*<div class="content-wrapper" style="padding:10px;">*@
                <div style="padding:10px;">
                    <div class="row" style="padding-bottom: 10px;">
                        <div class="col-md-4 font-bold text-2xl">
                            PIPELINE DATASET INFO
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <label>Pipeline Name</label>
                            <span id="txt_pipeline" class="mandatory" style="display:none;">*</span>
                            <select class="form-control" id="drp_pipeline" name="drp_pipeline">
                                <option value="">-- Select --</option>
                            </select>
                        </div>
                        <div class="col-md-4">
                            <label>Dataset Name</label>
                            <span id="txt_mappedds" class="mandatory" style="display:none;">*</span>
                            <select class="form-control" id="drp_mappedds" name="drp_mappedds">
                                <option value="">-- Select --</option>
                            </select>
                        </div>
                        <div class="col-md-4">
                            <input style="float: left;margin-top: 6%;" type="button" id='next' onclick="RefreshData()" class="refresh" value="Refresh" />
                        </div>

                    </div>
                    <fieldset>
                        <div class="form-card" style="height: 70vh;margin-top:1%;">
                            <div class="row" style="padding: 0px 16px;">
                                <div id="pipelineDSGrid"></div>
                            </div>
                        </div>
                    </fieldset>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
<script>
    $(document).ready(function () {
        const urlParams = new URLSearchParams(window.location.search);
        let userCode = "";
        if (urlParams != "") {
            userCode = urlParams.get('user_code');
        }
        else {
            userCode = 'Blank';
        }
        sessionStorage.setItem("userCode", userCode);
        listgrid([]);
        Getpipelines('', 'Active');
    });
</script>
<script>

    function RefreshData(){
        var ppl_code = $('#drp_pipeline').val();
        var ds_code = $('#drp_mappedds').val();
         GetpipelinedsList(ppl_code, ds_code);
    }

    function GetpipelinedsList(pipelinecode, datasetcode) {
        $.ajax({
            type: 'GET',
            url: '@Url.Action("GellPipelinedatasetInfo", "Report")?pipeline_code=' + pipelinecode + "&dataset_code=" + datasetcode,
            contentType: false,
            processData: false,
            cache: false,
            success: function (response) {
                var res = JSON.parse(response)
                var $grid = $("#pipelineDSGrid");

                // destroy previous grid if exists
                if ($grid.data("kendoGrid")) {
                    $grid.data("kendoGrid").destroy();
                    $grid.empty(); // remove leftover DOM
                }
                listgrid(res);
            },
            error: function (er) {
                alert(er)
                console.log(er)
            }
        });
    }

    function loadmappedds(pipeline_code) {
        $.ajax({
            type: "GET",
            url: '@Url.Action("GetDataSet", "Pipeline")?pipeline_code='+pipeline_code+"&source_fields="+''+"&datasetType="+'',
            dataType: "json",
            contentType: 'application/json; charset=utf-8',
            success: function (data) {
                console.log("data", data);
                var select = $("#drp_mappedds");

                // Clear existing options
                select.empty();

                // Add new options from the JSON data
                select.append($("<option>").attr("value", "").text("-- Select --"));

                $.each(data, function (index, item) {
                    select.append($("<option>").attr("value", item.dataset_code).text(item.dataset_name));
                });
                // $('#drp_mappedds').val(id + "-" + name);

            },
            error: function (er) {
                jAlert(er, "Error");
            }
        });
    }
</script>
<script>

    function listgrid(data) {
        try {
            $("#pipelineDSGrid").kendoGrid({

                dataSource: {
                    data: data,
                    schema: {
                        model: {
                            fields: {
                                connector_type: { type: "string" },
                                pipeline_code_name: { type: "string" },
                                dataset_code_name: { type: "string" },
                                upload_mode: { type: "string" },
                                key_field: { type: "string" },
                                key_field_desc: { type: "string" },
                                run_type: { type: "string" },
                                cron_expression: { type: "string" },
                                pipelinedet_status: { type: "string" },
                                updated_by: { type: "string" },
                                updated_date: { type: "string" }
                            }
                        }
                    },
                    pageSize: 15
                },
                height: 400,
                width: 1058,
                pageable: true,
                sortable: true,
                filterable: true,
                selectable: "single",
                toolbar: ["excel"],
                excel: {
                    fileName: "PipelineDatasetInfo.xlsx",
                    filterable: true,
                    allPages: true
                },
                columns: [
                    { field: "connector_type", title: "Conn Type", width: 100 },
                    { field: "pipeline_code_name", title: "Pipeline Code & Name", width: 200 },
                    { field: "dataset_code_name", title: "Dataset Code & Name", width: 200 },
                    { field: "upload_mode", title: "Upload Mode", width: 150 },
                    { field: "key_field", title: "key_field", width: 100, hidden: true },
                    { field: "key_field_desc", title: "key Field", width: 150 },
                    { field: "run_type", title: "Run Type", width: 100 },
                    { field: "cron_expression", title: "Cron Expression", width: 150 },
                    { field: "pipelinedet_status", title: "Status", width: 80 },
                    { field: "updated_by", title: "update by", width: 100 },
                    { field: "updated_date", title: "update date", width: 150,
                      template: "#= kendo.toString(kendo.parseDate(updated_date), 'yyyy-MM-dd HH:mm:ss') #"}
                ],
                resizable: true
            });
        } catch (err) {
            alert(err);
        }
    }


     function Getpipelines(runtype, pipeline_sts) {
        $.ajax({
            type: 'GET',
            url: '@Url.Action("GellAllPipelines", "Pipeline")?run_type=' + runtype + "&pipeline_status=" + pipeline_sts,
            //url: "../Pipeline/GellAllPipelines?run_type=" + runtype + "&pipeline_status=" + pipeline_sts,
            contentType: false,
            processData: false,
            cache: false,
            success: function (response) {
                 var select = $("#drp_pipeline");

                // Clear existing options
                select.empty();

                // Add new options from the JSON data
                select.append($("<option>").attr("value", "").text("-- Select --"));

                $.each(response, function (index, item) {
                    select.append($("<option>").attr("value", item.pipeline_code).text(item.pipeline_name));
                });
                // $('#drp_pipeline').val(id);
            },
            error: function (er) {
                alert(er)
                console.log(er)
            }
        });
    }

     $('#drp_pipeline').on('change', function () {
            var selectedValue = $(this).val();
            loadmappedds(selectedValue);
        });

</script>